[package]
name = "indices"
version = "0.1.0"
authors = ["Lukasz Czaplinski <git@scoiatael.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "5.0"
